export const INITIAL_LOAD_PRODUCTS = 'INITIAL_LOAD_PRODUCTS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const GET_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
export const FILTERED_QUERY = "FILTERED_QUERY";
export const LOAD_MORE = "LOAD_MORE";
export const GET_SHORT = 'GET_SHORT';